clase-3
JohanaMontenegro/CPFS2022 pull request #3
Opened 2022-07-28 16:51 UTC by JohanaMontenegro

ejercicios de la Clase 3

2022-07-28 20:12 UTC, SofiZ2001 commented on clase_3/votacion.ts
> +
Falta implementar esta funcion para saber donde vota cada uno

2022-07-28 20:31 UTC, SofiZ2001 requested changes
Resolver comentario en el archivo _votacion.ts_

2022-07-28 23:30 UTC, JohanaMontenegro commented on clase_3/votacion.ts
> +
si si despues de que lo cargue lo vi!

2022-08-04 04:06 UTC, SofiZ2001 approved these changes
LG2M

2022-08-04 04:06 UTC, merged