clase-4
JohanaMontenegro/CPFS2022 pull request #4
Opened 2022-07-28 16:56 UTC by JohanaMontenegro

Ejercicios de la Clase 4

2022-07-28 20:30 UTC, SofiZ2001 requested changes

2022-07-28 20:30 UTC, SofiZ2001 commented on clase_4/auto.ts
> +
Falta implementar esta función

2022-08-11 21:03 UTC, JohanaMontenegro commented on clase_4/auto.ts
> +
ya realice los cambios pedidos

2022-08-16 17:27 UTC, SofiZ2001 approved these changes
LG2M

2022-08-16 17:27 UTC, merged